# Generated by Django 5.2.14 on 2026-05-15 18:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('triptan', 'Triptan'), ('otc_analgesic', 'OTC Analgesic'), ('antiemetic', 'Antiemetic'), ('preventive', 'Preventive'), ('ergotamine', 'Ergotamine'), ('gepant', 'Gepant / CGRP Antagonist'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
                'ordering': ['type', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MigraineEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('migraine_type', models.CharField(choices=[('aura_only', 'Aura only (without headache)'), ('aura_with_headache', 'Aura with headache'), ('without_aura', 'Migraine without aura'), ('hemiplegic', 'Hemiplegic'), ('vestibular', 'Vestibular'), ('chronic', 'Chronic'), ('cluster', 'Cluster'), ('other', 'Other')], default='without_aura', max_length=20)),
                ('pain_level', models.PositiveSmallIntegerField(default=0, help_text="0=none, 1=little, 2=discomfort, 3=can't work, 4=debilitating, 5=hospital")),
                ('headache_location', models.CharField(blank=True, choices=[('unilateral_left', 'Unilateral (left)'), ('unilateral_right', 'Unilateral (right)'), ('bilateral', 'Bilateral'), ('frontal', 'Frontal'), ('temporal', 'Temporal'), ('occipital', 'Occipital'), ('vertex', 'Vertex'), ('retro_orbital', 'Retro-orbital')], default='', max_length=20)),
                ('headache_quality', models.CharField(blank=True, choices=[('throbbing', 'Throbbing / pulsating'), ('pressing', 'Pressing / tightening'), ('stabbing', 'Stabbing'), ('burning', 'Burning'), ('dull', 'Dull / aching')], default='', max_length=10)),
                ('disability_level', models.CharField(blank=True, choices=[('none', 'None — normal activity'), ('mild', 'Mild — reduced efficiency'), ('moderate', 'Moderate — significant impairment'), ('severe', 'Severe — bed rest required')], default='', max_length=10)),
                ('has_aura', models.BooleanField(default=False)),
                ('aura_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('visual_aura_locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('aura_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_hours_before', models.DecimalField(blank=True, decimal_places=1, help_text='Hours of sleep the night before onset', max_digits=4, null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, help_text='0=none … 5=extreme', null=True)),
                ('menstrual_related', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migraine_episodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'migraine episode',
                'verbose_name_plural': 'migraine episodes',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MigraineEpisodeMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_offset_minutes', models.IntegerField(blank=True, help_text='Minutes from episode start when taken (negative = taken before onset)', null=True)),
                ('dose', models.CharField(blank=True, default='', max_length=50)),
                ('effectiveness', models.BooleanField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_medications', to='migraine.migraineepisode')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episode_usages', to='migraine.medication')),
            ],
            options={
                'verbose_name': 'episode medication',
                'verbose_name_plural': 'episode medications',
                'ordering': ['taken_offset_minutes'],
                'unique_together': {('episode', 'medication')},
            },
        ),
        migrations.AddField(
            model_name='migraineepisode',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='episodes', through='migraine.MigraineEpisodeMedication', to='migraine.medication'),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('gi', 'Gastrointestinal'), ('sensory', 'Sensory'), ('neurological', 'Neurological'), ('autonomic', 'Autonomic'), ('psychological', 'Psychological'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'symptom',
                'verbose_name_plural': 'symptoms',
                'ordering': ['category', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='migraineepisode',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='migraine.symptom'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'Food & Drink'), ('hormonal', 'Hormonal'), ('stress', 'Stress'), ('sleep', 'Sleep'), ('environmental', 'Environmental'), ('physical', 'Physical Activity'), ('sensory', 'Sensory'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trigger',
                'verbose_name_plural': 'triggers',
                'ordering': ['category', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='migraineepisode',
            name='triggers',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='migraine.trigger'),
        ),
        migrations.AddIndex(
            model_name='migraineepisode',
            index=models.Index(fields=['user', '-started_at'], name='migraine_mi_user_id_eaf2db_idx'),
        ),
    ]
