# Generated by Django 5.2.14 on 2026-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migraine', '0003_seed_preset_symptoms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='migraineepisodemedication',
            unique_together=set(),
        ),
        # PostgreSQL cannot cast boolean → smallint directly; cast via int first.
        migrations.RunSQL(
            sql='ALTER TABLE migraine_migraineepisodemedication ALTER COLUMN effectiveness TYPE smallint USING effectiveness::int::smallint',
            reverse_sql='ALTER TABLE migraine_migraineepisodemedication ALTER COLUMN effectiveness TYPE boolean USING effectiveness::boolean',
        ),
        migrations.AlterField(
            model_name='migraineepisodemedication',
            name='effectiveness',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No relief'), (1, 'Partial relief'), (2, 'Full relief')], null=True),
        ),
    ]
